### ISSUE TITLE
Create script for rendering animations from the command line

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#1]
This script should be callable ala

blender --python render_animation.py

In this script, for a given blender-file, the .pam and .zip file should be loaded and rendering should be initiated. Optionally, frame- and time-settings should be adjusted.

**Comment by pherbers** [comment]
Should the settings for time and frames be passable by command line arguments or generated based on the timings?

**Comment by MartinPyka** [comment]
should be passable

**Comment by pherbers** [comment]
Created a script in examples/render_animation to automatically generate and render an animation. The docstring in the file explains how to use it.
