### ISSUE TITLE
check, whether py-menus are supported in Blender

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#10]
Blender versions before 2.72 do not have py-menus, raising an error when you try to start Blender (e.g. 2.70) with the most recent version of PAM. 

The error is caused by the following line

File "pam/gui/menus.py", line 30, in register
    kmi.properties.name = "pam.mapping_menu"
AttributeError: 'OperatorProperties' object has no attribute 'name'

Implement a control that checks whether this property exists before the assignment is executed.

**Comment by pherbers** [comment]
Before the menu is registered, the script now checks if the Blender version is above or equal to 2.72.
2d98d1fcf6c1e23b7da63b7006eca392ecc44edb
