### ISSUE TITLE
[parallelization] Connection visualization does not work

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#13]
When I try to visualize a connection, the following error is thrown

File "/blender-2.75a-linux-glibc211-x86_64/2.75/scripts/addons/pam/pam.py", line 499, in <listcomp>
    return sum([(path[i] - path[i - 1]).length for i in range(1, len(path))])
AttributeError: Vector subtraction: (Vector - tuple) invalid type for this operation

**Comment by pherbers** [comment]
Fixed in 3400972eb59711c8ea74ca5be710873754fd3c97. Just a few conversions to Vector were needed.
