### ISSUE TITLE
[parallelization] Problem when saving

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#15]
when I tried to save a network configuration, the following error occured

 File "Programs/blender-2.74-linux-glibc211-i686/2.74/scripts/addons/pam/model.py", line 157, in save
    pickle.dump(snapshot, open(path, "wb"))
_pickle.PicklingError: Can't pickle <class 'Vector'>: attribute lookup Vector on builtins failed

**Comment by pherbers** [comment]
Fixed in 099cd6fcf7b6b0b31eacf9fbdb9898aa1bda4d5a. When the model had connection errors during computation, the model could not be saved as there was no vector for the synapse, causing the conversion from vector to numpy array to fail when saving.
