### ISSUE TITLE
[pam_anim]Duplicate of neurons should adopt also modifiers and drivers

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#16]
When an object with modifiers and drivers is used as neuron-representations, its duplicates should also have the same configuration

**Comment by pherbers** [comment]
Done in 031a77396e61ceffdfbd25b4a6e666b570acfe2f. Modifiers and Drivers are now properly copied and some driver values are replaced with the duplicated object if that value was the source object. Array drivers, like position and rotation, might not work, but you can use single drivers instead.
