### ISSUE TITLE
[pam_anim] make pam_anim independent from csv-export of connectivity data

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#17]
I guess, we need to discuss this again, but in the long run it would be great, if loading just the pam file or just the zip file with the csv exported data are enough to get the data available for visualizing neurons and spikes.

**Comment by pherbers** [comment]
Already done, pam_anim only needs spike and delay data, everything else is taken from the pam model.
