### ISSUE TITLE
[master] provide estimate of conduction delay

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#19]
if user clicks on a neuron to visualize its connections and if custom properties are assigned to a particle system, use them to provide estimates of conduction delays

**Comment by pherbers** [comment]
Which custom properties should be used, and how are the conduction delays estimated?

**Comment by MartinPyka** [comment]
when a new particle-system is created with the PAM button, add a property to the particle-system (e.g. with the name 'delay'). The number here (e.g. default: 4) is multiplied with the average path length to give an estimate of the mean conduction delay and its standard deviation

**Comment by pherbers** [comment]
Done in d95dcbadfce3cdaa8c8ffaf6605bd363c76515cc. Now prints statistics like this:
    Visualizing connections for neuron 43 from CA1_sp -> CA1_sp.002 -> CA1_sp_axons_all -> Subiculum
    Using a delay modifier of  4.0
    Average connection length: 3.45200273899
    Standard deviation:        1.02603291233
    Maximum connection length: 6.11547120433
    Minimum connection length: 2.01925785993
    Visualizing connections for neuron 43 from CA1_sp -> CA1_sp.002 -> CA1_sp.006 -> CA1_sp.007 -> CA1_sp.008 -> EC_5
    Using a delay modifier of  4.0
    Average connection length: 17.7018588258
    Standard deviation:        0.668284652266
    Maximum connection length: 18.6964861923
    Minimum connection length: 15.5877953666
