### ISSUE TITLE
[pam-anim] Create texture with spike coding for animation of neurons

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#20]
Neuron representations in Blender can be easily generated by displaying any particle with a given mesh. However, animation of these meshes (e.g. change of material properties) is then not possible in the way we do it right now.

However, particle color / properties can be changed by using particle-id and frame number as texture coordinates for given texture. This texture can then decode the behavior of each particle (e.g. x-axis is particle-id and y-axis is time). 

Make a button in pam-anim that allows to export spike behavior of neurons as texture which can then be used as input for setting up the material

**Comment by pherbers** [comment]
Done in a58ae9204e65a68f849f58dbb0b6487a1f540ecd. There is a new button called "Generate spiking texture" in pam_anim that generates an image with frame on the x-Axis and neuron ID on the y-axis for the currently selected layer.

**Comment by MartinPyka** [comment]
Doesn't work for me. In particular, it is necessary, that the data are directly loaded from the zip file. Right now, it is necessary to press the generate-button in order to load the data and to create a texture.

Please note, that I also changed the specification of the exported spike data. so please create a new branch from master.

**Comment by MartinPyka** [comment]
alright, now I got it how to use the button and it works. Great! Added a hint, when no pre- or post-synaptic layer is selected. Anyway, the data should be loaded from the zip-file

**Comment by pherbers** [comment]
4e90a8bc33513fb66b80bdb09a7a575a472c0c25 now supports fadeout time. Also moved generate button to spike panel. Fixed having to press the generate button before generating a texture.
Next up is colours, I'll open a new branch spike_texture for that.

**Comment by pherbers** [comment]
Colors are working now, you can select the colorization method in the Layer Colors panel. Images are also automatically saved inside of the blend file.

**Comment by MartinPyka** [comment]
great!
