### ISSUE TITLE
Add optional material for Visualize Connections

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#22]
In the connections-panel add a field for selecting a material. When a material is selected, use it for all visualize-connection functions below (e.g. Connections at Cursor, Forward mapping at Cursor,...)

if there is no material proceed like in the current implementation

**Comment by pherbers** [comment]
Done in e9ce5b0863f9c4823f2ed37e381c2c9e2f484f90.
