### ISSUE TITLE
[pam_vis] Document spike recording-format for import and visualization

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#24]
For the visualization-article, it would be great to have a short description of the data format that pam_vis needs in order to visualize the spikes.

**Comment by pherbers** [comment]
Do you mean the data format for connections in model.py or the data format of the delays and spike timings used in pam_anim.py?

**Comment by pherbers** [comment]
Wrote a data structure summary in the [Wiki page](https://github.com/MartinPyka/Parametric-Anatomical-Modeling/wiki) explaining the file structure needed for spikes and delays.
