### ISSUE TITLE
[master] Provide debug information

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#25]
Add a button to the mapping panel (e.g. "Debug Mapping"), which goes through a mapping and checks for every unconnected pre- and post-neuron why it has not been connected. I am using right now PAM extensively and it happens all the time that I do not get neurons connected. It is pretty hard to figure this out for single neurons.

pam.py has already a debug mode in pam.computeMapping, which reports when a certain mapping comes to an end. Can you provide a more readable translation of what computeMapping in Debug mode returns to figure faster out what the problem is?

**Comment by pherbers** [comment]
I added a debug button in 266d01bcf96d543906003174fc3cf93bdc11712c and 5a3bd514ec654b58e886c409778b1933fbed9a2a that uses the debug mode of computeMapping similar to how visualizeForwardMapping does. Only the results of the debug function are printed, I'm not sure if this gives enough information for faster problem finding.
