### ISSUE TITLE
pam_anim: Reduce number of generated spikes

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#3]
Every time, the generate spikes button is hit, the number of spikes that are generated, doubles. See sample-file.

**Comment by pherbers** [comment]
The generated objects seem to be from an old version, the objects are now all stored in groups and only the objects in these groups will be deleted on clear visualization. Just delete the generated objects by hand and then everything should work.

**Comment by MartinPyka** [comment]
nope, it has something to do with the generation-process

**Comment by pherbers** [comment]
You were right! The timing list wasn't cleared before reading the timing file again, causing it to accumulate the timings. Fixed now!
