### ISSUE TITLE
[MSTree][uv_tree.py] interpolate path

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#7]
uv_center is now the root node of any tree. however, when the shift of the mean-value is very large,  (or in general, if the path between two nodes is very long), then the path does not lie on the layer anymore, if the layer is not level. Some intermediate nodes must therefore be added in uv-space and converted to 3d, in order to match the form of the 2d manifold. 
![screenshot from 2015-06-22 11 30 21](https://cloud.githubusercontent.com/assets/8008840/8279146/1a5a1158-18d2-11e5-806f-f8d117d9a0e0.png)

**Comment by pherbers** [comment]
Done in 42e5378551eada268e793888f161ecbd22ec81a4. An interpolation resolution can now be given to create_uv_tree as a parameter to slice long paths into multiple nodes.
