### ISSUE TITLE
[parallelization] Make number of THREADS a parameter for the UI

### ISSUE THREAD

**Issue by MartinPyka** [MartinPyka/Parametric-Anatomical-Modeling#8]
Make the parameter THREADS a value that can be configured in the UI. Additionally, this parameter should be given as an argument to the function pam.computeConnectivity() so that - as an option - we can run the algorithms from the command line.

**Comment by pherbers** [comment]
Done in d22cb374ca2b227833a6928ec28c0b42899e6f39. Number of Threads can now be chosen in Addon preferences. If Zero is chosen, os.cpu_count() is used.
